-- INSERT data for laender_behoerden (48 rows)
INSERT INTO laender_behoerden (code, land, region, beh_rde, website, anmerkung) VALUES
  ('DE', 'Deutschland', 'DACH', 'BfR / DGE', 'bfr.bund.de / dge.de', 'Höchstmengenempfehlungen'),
  ('AT', 'Österreich', 'DACH', 'AGES / BMG', 'ages.at', NULL),
  ('CH', 'Schweiz', 'DACH', 'BLV', 'blv.admin.ch', 'Nicht EU, eigene Regeln'),
  ('FR', 'Frankreich', 'WEST', 'ANSES', 'anses.fr', NULL),
  ('BE', 'Belgien', 'WEST', 'SPF Santé / CSS', 'health.belgium.be', NULL),
  ('NL', 'Niederlande', 'WEST', 'RIVM / Voedingscentrum', 'rivm.nl', 'Liberalere Obergrenzen'),
  ('LU', 'Luxemburg', 'WEST', 'Ministère de la Santé', 'sante.lu', 'Folgt meist BE/FR'),
  ('SE', 'Schweden', 'NORD', 'Livsmedelsverket', 'livsmedelsverket.se', NULL),
  ('DK', 'Dänemark', 'NORD', 'Fødevarestyrelsen', 'foedevarestyrelsen.dk', NULL),
  ('FI', 'Finnland', 'NORD', 'Ruokavirasto', 'ruokavirasto.fi', NULL),
  ('NO', 'Norwegen', 'NORD', 'Mattilsynet', 'mattilsynet.no', 'Nicht EU, EWR'),
  ('IS', 'Island', 'NORD', 'MAST', 'mast.is', 'Nicht EU, EWR'),
  ('IT', 'Italien', 'SÜD', 'Ministero della Salute', 'salute.gov.it', NULL),
  ('ES', 'Spanien', 'SÜD', 'AESAN', 'aesan.gob.es', NULL),
  ('PT', 'Portugal', 'SÜD', 'DGAV / ASAE', 'dgav.pt', NULL),
  ('GR', 'Griechenland', 'SÜD', 'EFET / EOF', 'efet.gr', NULL),
  ('MT', 'Malta', 'SÜD', 'MFA', 'mfa.gov.mt', NULL),
  ('CY', 'Zypern', 'SÜD', 'MOH', 'moh.gov.cy', NULL),
  ('PL', 'Polen', 'OST', 'GIS', 'gis.gov.pl', NULL),
  ('CZ', 'Tschechien', 'OST', 'SZPI', 'szpi.gov.cz', NULL),
  ('SK', 'Slowakei', 'OST', 'ŠVPS SR', 'svps.sk', NULL),
  ('HU', 'Ungarn', 'OST', 'NÉBIH', 'nebih.gov.hu', NULL),
  ('RO', 'Rumänien', 'OST', 'ANSVSA', 'ansvsa.ro', NULL),
  ('BG', 'Bulgarien', 'OST', 'BFSA', 'bfsa.bg', NULL),
  ('SI', 'Slowenien', 'OST', 'UVHVVR', 'gov.si/drzavni-organi/organi-v-sestavi/uprava-za-varno-hrano', NULL),
  ('HR', 'Kroatien', 'OST', 'HAH', 'hah.hr', NULL),
  ('EE', 'Estland', 'BALTIK', 'VTA', 'vet.agri.ee', NULL),
  ('LV', 'Lettland', 'BALTIK', 'PVD', 'pvd.gov.lv', NULL),
  ('LT', 'Litauen', 'BALTIK', 'VMVT', 'vmvt.lt', NULL),
  ('IE', 'Irland', 'ANDERE', 'FSAI', 'fsai.ie', NULL),
  ('UK', 'Großbritannien', 'ANDERE', 'FSA', 'food.gov.uk', 'Post-Brexit eigene Regeln'),
  ('EU', 'Europäische Union', '-', 'EFSA', 'efsa.europa.eu', 'EU-weite Obergrenzen'),
  ('US', 'Vereinigte Staaten', 'INTERNATIONAL', 'FDA', 'fda.gov', 'Ferrochel® GRAS; Sideral® als Dietary Supplement'),
  ('WHO', 'Weltgesundheitsorganisation', 'INTERNATIONAL', 'WHO', 'who.int', 'WHO-Leitlinien 2024 erwähnen Sucrosomial Iron!'),
  ('RU', 'Russland', 'INTERNATIONAL', 'Roszdravnadzor', '-', 'K-Mg-Aspartat als Arzneimittel (Asparkam®) verbreitet'),
  ('EFSA', 'European Food Safety Authority', 'EU', 'NDA Panel', 'efsa.europa.eu', 'Opinion 883 (2008): K-Aspartat bewertet aber NICHT in Anhang II aufgenommen'),
  ('JP', 'Japan', 'ANDERE', 'MHLW', 'https://www.mhlw.go.jp', '✅ Konjak traditionelles Lebensmittel (>1000 Jahre). Konnyaku.'),
  ('AU', 'Australien', 'ANDERE', 'FSANZ', 'https://www.foodstandards.gov.au', '⚠️ Konjak-Gelee eingeschränkt/verboten.'),
  ('PE', 'Peru', 'ANDERE', 'DIGESA', '-', '✅ Ursprungsland. Traditionelles Nahrungsmittel. Export-Kontrollen.'),
  ('BR', 'Brasilien (Herkunft Catuaba)', 'ANDERE', 'ANVISA', 'anvisa.gov.br', 'Catuaba Herkunftsland'),
  ('CN', 'China', 'ANDERE', 'CFDA', '-', '✅ Jiaogulan: Traditionelle Verwendung. Registriert als Functional Food.'),
  ('VN', 'Vietnam', 'ANDERE', 'MOH', '-', '✅ Jiaogulan: Traditionell als Tee bei Diabetes verwendet.'),
  ('EMA', 'Europäische Arzneimittel-Agentur', '-', 'EMA', 'ema.europa.eu', '⭐⭐ Cystadane® (Betain anhydrous) - Orphan Drug seit 2007 für Homocystinurie.'),
  ('NZ', 'Neuseeland', 'ANDERE', '-', '-', '✓ Herkunft von NZBC (New Zealand Black Currant) - besonders für Sport untersucht'),
  ('WADA', 'World Anti-Doping Agency', 'GLOBAL', 'WADA', 'https://www.wada-ama.org', '⛔⛔⛔ DHEA + 7-Keto-DHEA: Kategorie S1.1 (AAS) - VERBOTEN in- und außerhalb von Wettkämpfen!'),
  ('UA', 'Ukraine', 'NICHT-EU', '-', '-', '✓ Lagerstätte Sokyrnytsya.'),
  ('TH', 'Thailand', 'ASIEN', 'Thai Traditional Medicine Institute', '-', 'Ursprungsland von Kaempferia parviflora, Standards für PMF-Gehalt'),
  ('IN', 'Indien', 'ASIEN', 'FSSAI', '-', 'Ursprungsland von Slimvance/Laila Nutraceuticals')
;
